### ISSUE TITLE
LOHTML is not an object error

### ISSUE THREAD

**Issue by DougHennig** [RickStrahl/HelpBuilderReleases#77] opened 2018-09-17 20:35 UTC
I'm getting this error about every 30 seconds or so, which is making HTML Help Builder almost unusable right now.

#### Error Message:
LOHTML is not an object.

#### Module: 
PROCEDURE WWHELPFORM.OHELP.RENDERTOPICTOFILE D:\PROGRAM FILES (X86)\WEST WIND HTML HELP BUILDER\WWHELP.VCT

#### Line:
14

#### Call Stack:
1. d:\program files (x86)\west wind html help builder\wwhelp.exe | wwhelpmain | d:\program files (x86)\west wind html help builder\wwhelpmain.prg (292) |

----
2. d:\program files (x86)\west wind html help builder\wwhelp.vct | wwhelpform.tmrtoolbar.timer | d:\program files (x86)\west wind html help builder\wwhelp.vct (30) |
   thisform.DoEditOperation(lcName)
----
3. d:\program files (x86)\west wind html help builder\wwhelp.vct | wwhelpform.doeditoperation | d:\program files (x86)\west wind html help builder\wwhelp.vct (40) |
   			THISFORM.SaveTopic(.T.)
----
4. d:\program files (x86)\west wind html help builder\wwhelp.vct | wwhelpform.savetopic | d:\program files (x86)\west wind html help builder\wwhelp.vct (13) |
   	THISFORM.oHelp.RenderTopicToFile()
----
5. d:\program files (x86)\west wind html help builder\wwhelp.vct | wwhelpform.ohelp.rendertopictofile | d:\program files (x86)\west wind html help builder\wwhelp.vct (14) |
   loHTML.Write(  STRCONV(loHelp.RenderTopic(lcTopicId),9) )
----
6. errors.fxp | ON...  | d:\program files (x86)\west wind html help builder\errors.prg (120) |

----

#### Window:
WWHELPFORM

**Comment by RickStrahl** [comment] 2018-09-17 22:05
Hmmm... not sure. Anything change?

Can you turn off the preview as soon as you start Help Builder and see if that helps? 

It seems to me there's a problem either writing out the preview file or a problem with the HTML loading into the Web Browser for the preview.

**Comment by DougHennig** [comment] 2018-09-18 19:52
This is weird: it crashed on me a hundred times yesterday and now not at all today.

When it was crashing, it didn't matter whether the preview window was open or not (that was the first thing I tried), which seemed weird to me since I didn't think it would render if there's no preview.

The only thing that's different is I customized the template (topic.wcs) a little: I removed the <header class="content-title"> section.

It's been crashing on me at random for the past several weeks, but nothing reproducible and not as frequently as yesterday. I'll add more comments when it happens again.

**Comment by AntonijoSamarija** [comment] 2018-10-04 08:36
LOHTML is not an object.
Crashing randomly and instantly.
Even on only editing text.
**Disappear after updating drivers on my HP Laptop. (Strange)**
And editing text is now fast.

"Insert bookmark to another topic (Alt-O)" not work at all !
Only manual inserting bookmark.

"Comment or report problem with topic"
Forward to mail client body, Topic filename .htm is always uppercase.
Hosting servers are case sensitive.

**Comment by DougHennig** [comment] 2018-10-04 14:26
I see a similar issue to Antonijo: editing is quite slow. Lots of times, characters are missing because I'm typing faster than the editor can keep up, and I'm really not that fast of a typist.

**Comment by AntonijoSamarija** [comment] 2018-10-04 20:05
Hi 
Doug
When I update sata drivers and usb drivers on my hp laptop editing is fast and no more LOHTML errors
It is very strange.
Today Help Builder is migrated to Win 10 1809 october update and it works with no errors. 
Other issues are still present.

**Comment by RickStrahl** [comment] 2018-10-04 20:44
Yeah I've noticed that too and I think something happened with a recent update with Internet Explorer that caused that error to pop up - it's caused by an empty page  load to fail. I've made an internal fix that fixes that problem.

The slow typing perf problem I've also seen and I think that's caused either by the spell checker (on largish docs) or the preview.

Can you try the following individually:

* Turn off spell checking
* Turn off the preview

The editor itself is very fast, but it's some of the support features that can cause the Web Browser control to tie up the UI thread which can cause the stutter. It looks to me the spell checker is at fault here - if I turn it off especially on longer topics it works much better.

There are a few optimizations that can be made to the spell checker that I've made in Markdown Monster but haven't migrated back to HBP. Do let me know if turning the SC off makes it better.

**Comment by DougHennig** [comment] 2018-10-04 21:31
It's behaving for me right now (not crashing and typing speed fine) but next time it happens I'll try your suggestions.

**Comment by AntonijoSamarija** [comment] 2018-10-11 07:09
When editing text. 
Undo does not work.
When selecting text and want to move somewhere on another location in text moving is strange it is like moving entire editing pane. It is hard to know where selected is moving seems all blurry.

**Comment by RickStrahl** [comment] 2019-02-18 02:26
Ok so I've done some more work on this problem. Although I haven't been able to fix this issue entirely there's now code in place that catches the error which is related to the preview rendering and ignores it and goes on. This may result in an occasional preview update failing, but it won't hang the application. 

The error is caused by HB not being able to create the preview file because it's locked. There's no additional code that ensures that the file is released after rendering and error handling that simply aborts a preview operation and waits for the next refresh cycle to refresh the preview. This doesn't fix the problem completely but it minimizes the occurrance, and when it does occur now it ignores the error and continues (since it's a non-fatal preview refresh that will catch up).

Not ideal, but that's as good as I can track this. In my extensive editing I've done in the last couple of weeks I have not seen this problem return. I didn't notice any issues with the preview either so this is probably a good fix going forward.

Fixed in 1.15+.

**Closed as completed by RickStrahl** 2019-02-18 02:26 UTC
