### ISSUE TITLE
Options dialog not saving changes to Theme on Editor page

### ISSUE THREAD

**Issue by DougHennig** [RickStrahl/HelpBuilderReleases#3] opened 2015-08-13 19:20 UTC
This just may not be implemented yet but changes to Theme on the Editor page of the Options dialog aren't saved.

**Comment by RickStrahl** [comment] 2015-08-13 21:37
Should be working, but you have to reload the editor for the changes to show. So either shut down and restart or switch to preview (in app) and back.

**Comment by RickStrahl** [comment] 2015-08-14 00:00
Hmmm... ok I think i know what the issue is with this. Can you retry using "Run As Administrator" - I bet that works.

The problem is that the configuration for these values are stored in the install directory (Program Files\Help Builder\Editors\AceConfig.js). Unfortunately that file cannot moved to a safe location like Document or AppData because it has to be loaded from the same folder as the editor HTML. 

Not really sure why it's not working - those values should still be moved to virtual storage by UAC, but apparently that's not happening. The save operation doesn't actually fail.

The only way to fix this will be to move the entire Editors folder to AppData (or whereever) - not looking forward to that. Any ideas why UAC wouldn't be using the Virtual Storage to forward this write operation automatically?

**Comment by DougHennig** [comment] 2015-08-14 19:14
It looks like wwHelp_EditorSettings.js is referenced in wwHelp_Editor.htm. Why not put any files that potentially need to be writable (wwHelp_Editor.css looks like another candidate) in a subdirectory that your installer makes writable? That's what I do with Stonefield Query: some files a user may need to change go in a Data subdirectory of the program folder and the installer gives full permission to everyone to that one folder. The reason I do that instead of using App_Data is because I need that folder to be global to all users and the user may install it on a server drive where there is no App_Data folder.

I'm not sure why UAC is treating this differently than other files that get virtualized. Is there a manifest on wwHelp.exe that tells Windows it's Vista (and later) aware?

**Comment by RickStrahl** [comment] 2015-08-15 07:03
All those files are already in a separate folder so I could just make that folder writable. Didn't think that the installer can actually make that happen - I have to check.

As to manifest - I'm using the stock Fox manifest which I believe is Vista aware. It may have to do with the fact that the file is .js script file and it's considered and executable.

**Comment by RickStrahl** [comment] 2015-08-15 19:22
Fixed in build 5.0.61

Added support code in Help Builder using SetAcl() from wwutils that is called from the installer. The editors folder is now read-write so config settings can be changed as well as making the other editor files in that folder editable without admin permissions. Also added HelpBuilder_Extensions.prg/fxp to be writable as well as this can cause launch problems if the PRG is changed.

Thanks Doug for pointing in the right direction.

Sidenote: MSDN UAC documentation for virtual folder re-direction mentions that Microsoft will remove that feature in the future. I think that future is here with Windows 10 and that's why it's not working for me.

**Closed as completed by RickStrahl** 2015-08-15 19:22 UTC
Labels: bug

**Comment by DougHennig** [comment] 2015-08-17 15:23
Virtualization hasn't been removed yet: when I fire up VFP and create a program without changing folders, the program is created in C:\Users\dhennig\AppData\Local\VirtualStore\Program Files (x86)\Microsoft Visual FoxPro 9. So, something else is preventing it from happening. Don't know what.

**Comment by RickStrahl** [comment] 2015-08-17 19:34
Hmm... yes this is really odd. I see folders for some of my other applications - it's dumping compiled FXP files into the virtual store for the Proxy Generator and the message reader, but there's nothing for Help Builder. It's almost like virtualization is off for it.

Anyway for now the problem is solved by making the Editors folder writable - did that solve your problem now? You should be able to update the theme and other settings on that page.

**Comment by DougHennig** [comment] 2015-08-18 15:33
Yes, it's working correctly now.
