### ISSUE TITLE
Error if double-click in editboxes

### ISSUE THREAD

**Issue by DougHennig** [RickStrahl/HelpBuilderReleases#26] opened 2015-11-30 20:54 UTC
Double-clicking in any of the editboxes (e.g. Syntax, Parameters, Returns, Example) gives an "OLE IDispatch exception code 0 from wwDotNetBridge: Parameter is not valid" error.

**Comment by RickStrahl** [comment] 2015-11-30 21:33
Are you on .150? I think this issue was addressed in a recent update.

Double clicking should give you the Markdown editor as a separate window. I just double checked in my installed app and I don't get the error.

**Comment by RickStrahl** [comment] 2015-11-30 21:36
Oh now I remember - was caused by an overridden method that had commented code in it but was missing the base overloaded parameters. That should be fixed in .150.

**Comment by DougHennig** [comment] 2015-11-30 21:36
No, I'm using 148. I'll try it in 150.

**Comment by RickStrahl** [comment] 2015-11-30 22:28
FWIW in .150 you can now also use Alt-UpArrow to switch to the external editor and back into the original control.

Gotta figure out a way to make this visible somehow.

**Comment by RickStrahl** [comment] 2015-12-04 10:04
Did you try out .150? Did this now work? It should :-)

**Comment by DougHennig** [comment] 2015-12-07 21:25
I just tried it in 150 -- same error.

**Comment by RickStrahl** [comment] 2015-12-11 12:19
Can you try this again in .167 Doug? Double Clicking or Alt-Up opens the external editor. It's possible the previous version did not have the updated version of wwDotnetBridge.dll that was required which might have caused this problem.

**Comment by DougHennig** [comment] 2015-12-11 19:32
Same error. wwDotNetBridge.dll is 131,584 bytes, dated 12/09/2015 2:37 PM, and version 6.0.0.0.

**Comment by RickStrahl** [comment] 2015-12-11 23:13
Can you send me the Errorlog.dbf from the Documents\Help Builder Projects folder or attach here as a zip.

I'm not sure what could be different here as I'm running the installed application and no problem here.

**Comment by DougHennig** [comment] 2015-12-13 15:53
I checked that file and the error isn't logged there (latest record is dated 10/23/2015).

**Comment by RickStrahl** [comment] 2015-12-13 21:16
Hmmm... odd. I'm kind of at a loss a) why this is happening and b) why you're not getting the error logged.

It sure sounds like you're getting the wrong version of wwDotnetBridge somehow. 

Can you double check and ensure there is no wwDotnetBridge.dll in the root folder? The root folder should only hold two dlls: zlib and hunspell. All the other DLLs including wwDotnetBridge.dll should be in the /bin folder.

Maybe I can give you custom build that explicitly captures the exception on the form load and just show a message box if it fails.

**Comment by RickStrahl** [comment] 2015-12-14 11:25
I've pushed up version .175. Give that a try and see if that works for you.

In case it doesn't, this version adds new logging into a errorlog.txt file in the `<documents>\Html Help Builder Projects` folder. The new logging info includes the callstack which hopefully should give more info.

**Comment by RickStrahl** [comment] 2015-12-14 14:33
Ok - so i found the problem. Related to a custom menu system on the edit form. Images were working on my machine because the files are actually there - on other machines the files are in the project. Code will need to be changed to read the binary data and use that to create transparent disabled images for toolbars and other items.

Should be fixed in .180.

**Closed as completed by RickStrahl** 2015-12-14 14:33 UTC

**Comment by DougHennig** [comment] 2015-12-14 19:04
Yes, it's fixed in 180. However, when I double-click, I see that a new window is created but it must be off-screen. If I shift-right-click the window in the task bar and choose Move, press an arrow key, then move my mouse, the window seems to appear from the bottom of my monitor. Moving it somewhere, closing it, and double-clicking again does the same thing.

**Comment by RickStrahl** [comment] 2015-12-14 19:49
Yikes. Yes the window is initially created offscreen due to the ActiveX control in it and avoiding some nasty flicker. But it should snap into place at a small relative offset to the main form. However, the offset is negative initially.

I had a major bug last night after I released and I had to pull out some code and since then I've had problems with the form popping up in a weird place, not respecting the values that are passed in.

I'll check out and see. This should hopefully be easy to fix.
